### ISSUE TITLE
strongly suggest to remove private key and address in doc

### ISSUE THREAD

**Issue by PirateCode-eth** [ethereumfollowprotocol/contracts-beta#4]
I had a experience about a public private dev key and accidentally transfer the mainnet ETH to the dev address before and the hacker get the money out immediately.

Every exposed private key is being controlled by hackers so it's a strong good practice that don't share the private key to devs, send them testnet ETH if they don't have it if they share their address.

**Comment by o-az** [comment]
> I had a experience about a public private dev key and accidentally transfer the mainnet ETH to the dev address before and the hacker get the money out immediately.
> 
> Every exposed private key is being controlled by hackers so it's a strong good practice that don't share the private key to devs, send them testnet ETH if they don't have it if they share their address.

Thanks for looking out. This key is ok to share. It's for testing and autogenerated by the local testing tool [`anvil`](https://book.getfoundry.sh/anvil/). It's always the same for all `anvil` users so anyone can get private keys for this address by running `anvil` locally:

![CleanShot 2023-12-01 at 19 06 41@2x](https://github.com/ethereumfollowprotocol/beta-contracts/assets/23618431/701be2bf-643e-4cab-ae1b-e943f821e84b)
